#pragma once
#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 412

#define MOVEMENT_SPEED 240
#define JUMP_FORCE_DECREMENT 800.0f
#define INITIAL_JUMP_FORCE 600.0f
#define GRAV_FORCE 10.0f
#define MAX_ACCELERATION 1.0f
#define ACCELERATION_RATE 0.03f

#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_HEIGHT 32
#define TILE_WIDTH 32

#define SCREENSHAKE_DURATION 0.25f;

#define INJURED_TIME 3.0f
#define KOOPA_SPEED 60

#define ANIMATION_DELAY 0.1f

#endif // !_CONSTANTS_H
